plugins {
    id 'com.android.library'
}

android {
    namespace 'com.duy.decompiler'
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 34
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
}
