plugins {
    id 'com.android.library'
}

android {
    namespace 'com.duy.bouncycastle'
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api 'org.bouncycastle:bcpkix-jdk15on:1.70'
    api 'org.bouncycastle:bcprov-jdk15on:1.70'
}
